services:
  db:
    image: postgres:latest
    container_name: adquick
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adquick123
      POSTGRES_DB: adquick
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: